---
# Example playbooks demonstrating different post-renderer use cases

# Example 1: Simple global tag replacement
- name: Deploy SMO with stable tags
  hosts: smo_servers
  become: yes
  vars:
    deployment_flavor: "default"
    enable_post_renderer: true
    global_image_tag: "stable"
  roles:
    - smo_deploy

---
# Example 2: Air-gapped deployment with local registry
- name: Deploy SMO in air-gapped environment
  hosts: smo_servers
  become: yes
  vars:
    deployment_flavor: "default"
    enable_post_renderer: true
    image_tag_mappings:
      - "nexus3.onap.org:10001/* -> harbor.local:5000/onap/*"
      - "docker.io/* -> harbor.local:5000/*"
      - "o-ran-sc/* -> harbor.local:5000/o-ran-sc/*"
  roles:
    - smo_deploy

---
# Example 3: Pin specific component versions
- name: Deploy SMO with pinned versions
  hosts: smo_servers
  become: yes
  vars:
    deployment_flavor: "default"
    enable_post_renderer: true
    image_tag_mappings:
      - "onap/aai:* -> onap/aai:1.12.3"
      - "onap/sdc:* -> onap/sdc:1.10.2"
      - "onap/sdnc:* -> onap/sdnc:2.5.1"
      - "onap/policy-apex-pdp:* -> onap/policy-apex-pdp:2.8.2"
      - "o-ran-sc/nonrtric-plt-policymanagementservice:* -> o-ran-sc/nonrtric-plt-policymanagementservice:1.2.3"
  roles:
    - smo_deploy

---
# Example 4: Use custom patched images
- name: Deploy SMO with custom patches
  hosts: smo_servers
  become: yes
  vars:
    deployment_flavor: "default"
    enable_post_renderer: true
    image_tag_mappings:
      # Use patched AAI
      - "nexus3.onap.org:10001/onap/aai:1.12.3 -> myregistry.com/onap/aai:1.12.3-security-patch"
      # Use custom SDNC
      - "nexus3.onap.org:10001/onap/sdnc:2.5.1 -> myregistry.com/onap/sdnc:2.5.1-custom"
      # Keep others as default
  roles:
    - smo_deploy

---
# Example 5: Component-specific tags
- name: Deploy SMO with component-specific tags
  hosts: smo_servers
  become: yes
  vars:
    deployment_flavor: "default"
    enable_post_renderer: true
    onap_image_tag: "2.8.0"
    nonrtric_image_tag: "1.2.3"
  roles:
    - smo_deploy

---
# Example 6: Mixed strategy
- name: Deploy SMO with mixed tag strategy
  hosts: smo_servers
  become: yes
  vars:
    deployment_flavor: "default"
    enable_post_renderer: true
    # Default everything to stable
    global_image_tag: "stable"
    # But override specific components
    image_tag_mappings:
      - "onap/aai:* -> onap/aai:1.12.4"
      - "onap/sdnc:* -> onap/sdnc:2.5.2"
      # And use local registry for some
      - "nexus3.onap.org:10001/onap/policy-* -> harbor.local:5000/onap/policy-*"
  roles:
    - smo_deploy

---
# Example 7: Testing with development images
- name: Deploy SMO with development images
  hosts: smo_servers
  become: yes
  vars:
    deployment_flavor: "small"
    enable_post_renderer: true
    image_tag_mappings:
      # Use dev/snapshot tags for testing
      - "*:latest -> dev"
      - "onap/aai:* -> onap/aai:1.13.0-SNAPSHOT"
      - "o-ran-sc/nonrtric-* -> o-ran-sc/nonrtric-*:latest"
  roles:
    - smo_deploy

---
# Example 8: Multi-registry deployment
- name: Deploy SMO from multiple registries
  hosts: smo_servers
  become: yes
  vars:
    deployment_flavor: "default"
    enable_post_renderer: true
    image_tag_mappings:
      # ONAP from internal mirror
      - "nexus3.onap.org:10001/onap/* -> mirror.internal.com/onap/*"
      # O-RAN from public registry
      - "o-ran-sc/* -> docker.io/oransc/*"
      # Third-party from harbor
      - "docker.io/library/* -> harbor.internal.com/library/*"
  roles:
    - smo_deploy

---
# Example 9: Incremental update deployment
- name: Deploy SMO with selective updates
  hosts: smo_servers
  become: yes
  vars:
    deployment_flavor: "default"
    enable_post_renderer: true
    # Update only AAI and Policy components
    image_tag_mappings:
      - "onap/aai:1.12.3 -> onap/aai:1.12.4"
      - "onap/policy-*:2.8.1 -> onap/policy-*:2.8.2"
    # Keep all other components at their default versions
  roles:
    - smo_deploy

---
# Example 10: Complete custom registry mapping
- name: Deploy SMO with complete registry remapping
  hosts: smo_servers
  become: yes
  vars:
    deployment_flavor: "large"
    enable_post_renderer: true
    post_renderer_config: "/etc/smo/custom-post-renderer.yaml"
    image_tag_mappings:
      # Map all upstream registries to internal
      - "nexus3.onap.org:10001/* -> nexus.mycompany.com:8443/onap/*"
      - "docker.io/* -> nexus.mycompany.com:8443/dockerhub/*"
      - "o-ran-sc/* -> nexus.mycompany.com:8443/oran/*"
      - "gcr.io/* -> nexus.mycompany.com:8443/gcr/*"
      - "quay.io/* -> nexus.mycompany.com:8443/quay/*"
  roles:
    - smo_deploy
  post_tasks:
    - name: Verify all images are from internal registry
      shell: |
        kubectl get pods -n onap -o jsonpath='{range .items[*]}{.spec.containers[*].image}{"\n"}{end}' | \
        grep -v "nexus.mycompany.com" || echo "All images from internal registry"
      register: image_check
    
    - name: Display image verification
      debug:
        var: image_check.stdout_lines