---
# Example playbook for SMO uninstallation
# File: smo_uninstall_playbook.yml

- name: Uninstall SMO Components from Kubernetes Cluster
  hosts: all
  become: yes
  gather_facts: yes
  
  vars:
    # Override defaults if needed
    namespace_deletion_timeout: 600
    ignore_cleanup_errors: yes
  
  pre_tasks:
    - name: Verify kubectl is installed
      ansible.builtin.command: kubectl version --client
      changed_when: false
      register: kubectl_version
    
    - name: Display kubectl version
      ansible.builtin.debug:
        msg: "kubectl version: {{ kubectl_version.stdout_lines[0] }}"
    
    - name: Verify helm is installed
      ansible.builtin.command: helm version --short
      changed_when: false
      register: helm_version
    
    - name: Display helm version
      ansible.builtin.debug:
        msg: "{{ helm_version.stdout }}"
    
    - name: Confirm uninstallation
      ansible.builtin.pause:
        prompt: "This will DELETE all SMO components. Press Enter to continue or Ctrl+C to abort"
      when: not ansible_check_mode
  
  roles:
    - role: smo_undeploy

  post_tasks:
    - name: Display completion message
      ansible.builtin.debug:
        msg: |
          ===================================================
          SMO Uninstallation completed!
          
          Please verify that all resources have been removed:
          - kubectl get namespaces
          - kubectl get pv
          - ls -la /dockerdata-nfs /dockerdata
          ===================================================
